In [3]:
import pybaseball
from pybaseball import  playerid_lookup
from pybaseball import  statcast_pitcher
import json

In [4]:
playerid_lookup('imanaga', 'shota')

Gathering player lookup table. This may take a moment.

,name_last,name_first,key_mlbam,key_retro,key_bbref,key_fangraphs,mlb_played_first,mlb_played_last
0,imanaga,shota,684007,imans001,imanash01,33829,2024.0,2024.0

In [5]:
imanaga_stats = statcast_pitcher('2024-03-28', '2025-03-22', 684007)

Gathering Player Data

In [6]:
imanaga_stats.head()

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,description,...,n_thruorder_pitcher,n_priorpa_thisgame_player_at_bat,pitcher_days_since_prev_game,batter_days_since_prev_game,pitcher_days_until_next_game,batter_days_until_next_game,api_break_z_with_gravity,api_break_x_arm,api_break_x_batter_in,arm_angle
0,FF,2025-03-18,92.3,2.63,5.41,"Imanaga, Shota",624424,684007,field_out,hit_into_play,...,2,1,NaN,NaN,NaN,1.0,1.23,1.14,1.14,NaN
1,ST,2025-03-18,79.6,2.96,5.25,"Imanaga, Shota",624424,684007,NaN,ball,...,2,1,NaN,NaN,NaN,1.0,3.29,-1.23,-1.23,NaN
2,FS,2025-03-18,83.6,2.70,5.30,"Imanaga, Shota",571771,684007,field_out,hit_into_play,...,2,1,NaN,NaN,NaN,1.0,2.80,1.04,-1.04,NaN
3,FS,2025-03-18,81.9,2.67,5.27,"Imanaga, Shota",571771,684007,NaN,swinging_strike,...,2,1,NaN,NaN,NaN,1.0,3.07,1.30,-1.30,NaN
4,FF,2025-03-18,91.0,2.66,5.34,"Imanaga, Shota",571970,684007,walk,ball,...,2,1,NaN,NaN,NaN,1.0,1.35,0.65,0.65,NaN

In [7]:
imanaga_stats.columns

Index(['pitch_type', 'game_date', 'release_speed', 'release_pos_x',
       'release_pos_z', 'player_name', 'batter', 'pitcher', 'events',
       'description',
       ...
       'n_thruorder_pitcher', 'n_priorpa_thisgame_player_at_bat',
       'pitcher_days_since_prev_game', 'batter_days_since_prev_game',
       'pitcher_days_until_next_game', 'batter_days_until_next_game',
       'api_break_z_with_gravity', 'api_break_x_arm', 'api_break_x_batter_in',
       'arm_angle'],
      dtype='object', length=113)

In [8]:
imanaga_stats['release_spin_rate']

0       2572.0
1       2540.0
2       1200.0
3       1128.0
4       2336.0
         ...
2812    1010.0
2813    2505.0
2814    2382.0
2815    2552.0
2816    2517.0
Name: release_spin_rate, Length: 2817, dtype: float64

In [9]:
subset_imanaga = imanaga_stats[['game_date', 'pitch_type', 'plate_x', 'plate_z', 'effective_speed', 'release_spin_rate', 'description']]
subset_imanaga

,game_date,pitch_type,plate_x,plate_z,effective_speed,release_spin_rate,description
0,2025-03-18,FF,0.08,3.00,91.8,2572.0,hit_into_play
1,2025-03-18,ST,-0.47,1.29,79.1,2540.0,ball
2,2025-03-18,FS,-0.17,2.34,NaN,1200.0,hit_into_play
3,2025-03-18,FS,0.81,1.17,81.2,1128.0,swinging_strike
4,2025-03-18,FF,-0.31,3.47,90.0,2336.0,ball
...,...,...,...,...,...,...,...
2812,2024-04-01,FS,0.53,1.35,84.0,1010.0,swinging_strike
2813,2024-04-01,FF,0.15,3.61,92.6,2505.0,foul
2814,2024-04-01,FF,-0.06,2.85,92.5,2382.0,hit_into_play
2815,2024-04-01,FF,-1.30,3.26,93.7,2552.0,ball
2816,2024-04-01,FF,0.21,2.32,91.8,2517.0,called_strike

In [10]:
subset_imanaga['pitch_type'].unique()

array(['FF', 'ST', 'FS', 'CU', 'SL', 'SI', nan, 'CH', 'CS', 'FC'],
      dtype=object)

In [11]:
subset_imanaga['pitch_type'].value_counts()

pitch_type
FF    1408
FS     843
ST     225
CH     100
CU      85
SI      59
FC      12
SL       1
CS       1
Name: count, dtype: int64

In [12]:
subset_imanaga.to_json('imanaga.json', orient='records')